// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    forecast_by_city: {
        name: "forecast_by_city";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          city: string;
          /** @sqlType BIGINT */
          forecast_trips: number;
        }>;
      };
    forecast_by_day: {
        name: "forecast_by_day";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          day: string;
          /** @sqlType BIGINT */
          forecast_trips: number;
        }>;
      };
    kpi_fleet: {
        name: "kpi_fleet";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          fleet_size: number;
          /** @sqlType BIGINT */
          at_risk_7d: number;
          /** @sqlType BIGINT */
          need_now: number;
          /** @sqlType DOUBLE */
          avg_anomaly: number;
        }>;
      };
    kpi_overview: {
        name: "kpi_overview";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DOUBLE */
          revenue_bn_idr: number;
          /** @sqlType BIGINT */
          completed_trips: number;
          /** @sqlType DECIMAL(15,4) */
          cancellation_rate: number;
          /** @sqlType DECIMAL(15,4) */
          no_driver_rate: number;
          /** @sqlType DOUBLE */
          avg_surge: number;
          /** @sqlType DOUBLE */
          avg_rating: number;
        }>;
      };
    nodriver_by_hour: {
        name: "nodriver_by_hour";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType INT */
          hour_of_day: number;
          /** @sqlType DECIMAL(15,4) */
          no_driver_rate: number;
        }>;
      };
    outcome_mix: {
        name: "outcome_mix";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          status: string;
          /** @sqlType BIGINT */
          trips: number;
        }>;
      };
    persona_drivers: {
        name: "persona_drivers";
        parameters: {
          /** STRING - use sql.string() */
          persona: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          driver_id: string;
          /** @sqlType STRING */
          driver_name: string;
          /** @sqlType STRING */
          phone: string;
          /** @sqlType STRING */
          nik: string;
          /** @sqlType STRING */
          home_city: string;
          /** @sqlType STRING */
          fleet_brand: string;
        }>;
      };
    persona_summary: {
        name: "persona_summary";
        parameters: {
          /** STRING - use sql.string() */
          persona: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BOOLEAN */
          pii_visible: boolean;
          /** @sqlType STRING */
          allowed_city: string;
          /** @sqlType BIGINT */
          visible_trips: number;
          /** @sqlType BIGINT */
          visible_cities: number;
        }>;
      };
    persona_trips_by_city: {
        name: "persona_trips_by_city";
        parameters: {
          /** STRING - use sql.string() */
          persona: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          city: string;
          /** @sqlType BIGINT */
          trips: number;
          /** @sqlType DOUBLE */
          revenue_bn_idr: number;
        }>;
      };
    revenue_by_day: {
        name: "revenue_by_day";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          day: string;
          /** @sqlType DOUBLE */
          revenue_bn_idr: number;
        }>;
      };
    risk_by_brand: {
        name: "risk_by_brand";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          fleet_brand: string;
          /** @sqlType BIGINT */
          at_risk_7d: number;
        }>;
      };
    top_zones: {
        name: "top_zones";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          pickup_zone: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          zone_type: string;
          /** @sqlType BIGINT */
          trips: number;
          /** @sqlType DOUBLE */
          revenue_m_idr: number;
          /** @sqlType DOUBLE */
          avg_surge: number;
        }>;
      };
    trips_by_city: {
        name: "trips_by_city";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          city: string;
          /** @sqlType BIGINT */
          trips: number;
        }>;
      };
    vehicles_at_risk: {
        name: "vehicles_at_risk";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          vehicle_id: string;
          /** @sqlType STRING */
          fleet_brand: string;
          /** @sqlType BIGINT */
          risk_pct: number;
          /** @sqlType DOUBLE */
          anomaly_score: number;
          /** @sqlType DOUBLE */
          brake_wear_pct: number;
          /** @sqlType DOUBLE */
          battery_v: number;
          /** @sqlType BIGINT */
          km_since_service: number;
          /** 1 if the vehicle needs maintenance now (ML target) */
          needs_service_now: number;
        }>;
      };
    whoami: {
        name: "whoami";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          identity: string;
          /** @sqlType BOOLEAN */
          is_ws_admin: boolean;
        }>;
      };
  }
}
